stages:
  - build
  - deploy
  - enable_merge

build_job:
  stage: build
  tags: 
    - tomhp
  script:
    ./debBuild.sh
  artifacts:
    paths:
      - ./build_deb/  
  only:
    - embtom-1.6.4

deploy_job:
  stage: deploy
  tags: 
    - tomhp
  script:
    - cd ./build_deb
    - cp * /media/volume1/ci_projects/snapshot/fmtlib
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic libfmt-dev
    - reprepro -b /media/volume1/reprepo/ -A amd64 remove bionic libfmt-doc
    - reprepro --ignore=wrongdistribution -b /media/volume1/reprepo/ -V include bionic fmtlib_6.0.0_amd64.changes
  when: on_success
  only:
    - embtom-6.0.0

enable_merge:
  stage: enable_merge    
  tags: 
    - tomhp
  script:
    - ./debBuild.sh
  only: 
    - merge_requests




